os: linux
language: node_js
node_js: node
cache:
  yarn: true
sudo: false
matrix:
  fast_finish: true
install:
- travis_retry yarn install --production
script:
- yarn run build
after_success:
- if [ ${TRAVIS_PULL_REQUEST} = "false" ];
  then bash deploy.sh;
  else echo "Nothing to deploy";
  fi
notifications:
  email: false
