language: php

cache:
  directories:
    - node_modules
    - tasks

sudo: false

node_js:
  - iojs

php:
  - 5.4.45

matrix:
  fast_finish: true

before_install:
  - travis_retry npm install -g grunt-cli
  - travis_retry gem install sass

install: travis_retry npm install --save-dev

before_script: phplint 'src/**/*php'

script: grunt

