os: linux
dist: xenial
language: node_js
node_js: node
cache:
  yarn: true
sudo: false
matrix:
  fast_finish: true
script: yarn build
after_success:
- if [ ${TRAVIS_PULL_REQUEST} = "false" ];
  then bash deploy.sh;
  fi
notifications:
  email: false
