language: php
cache:
  directories:
    - node_modules
sudo: false
dist: trusty
node_js: node
php: 5.4.45
matrix:
  fast_finish: true
before_install:
  - npm update && npm prune
  - gem update bundler
  - travis_retry npm install -g grunt-cli
  - travis_retry gem install sass
install: travis_retry npm install --save-dev
before_script: phplint 'src/**/*php'
script: grunt

